### ISSUE TITLE
error using genpass / retrieving password

### ISSUE THREAD

**Issue by benedict-beuscher** [rchatterjee/nocrack#2]
after generating (and storing) a password it often is shown different by the getpass-method. 
Sometimes, however, the correct password is returned.
![issue2](https://cloud.githubusercontent.com/assets/13997397/9518982/6a509dae-4cbb-11e5-9c15-e8b09e7dfeb0.png)

**Comment by rchatterjee** [comment]
Fixed them. Please pull. Thanks for pointing them out. The branch was off from the current local dev branch. 

[nocrack] [master]$ ./honey_client -genpass mpw123 google.com
OrderedDict([('google.com', 'kqzTn_z+D1')])
[nocrack] [master]$ ./honey_client -getpass mpw123 google.com
OrderedDict([(u'google.com', 'kqzTn_z+D1')])
