### ISSUE TITLE
ZeroDivisionError with some password

### ISSUE THREAD

**Issue by benedict-beuscher** [rchatterjee/nocrack#3]
Got another issue today. Storing some (long) passwords yields in a zeroDivisionError
![screenshot - 31 08 2015 - 15 46 45](https://cloud.githubusercontent.com/assets/13997397/9580088/7fdf5914-4ff7-11e5-9dfc-20753ee559a1.png)

thanks for the other fixes btw ;)

**Comment by rchatterjee** [comment]
Hey,
I fixed this bug, and pushed the updated code. Feel free to pull and check.

On Mon, Aug 31, 2015 at 9:47 AM, benedict-beuscher <notifications@github.com
