### ISSUE TITLE
KeyError with some masterpws

### ISSUE THREAD

**Issue by benedict-beuscher** [rchatterjee/nocrack#4]
Hi sorry to bother you again, one more issue i wanted to report:
trying to brute force a vault, i get a keyError-exception with some passwords
![screenshot - 24 09 2015 - 13 29 27](https://cloud.githubusercontent.com/assets/13997397/10072314/c3c33ff2-62c0-11e5-8bbe-f8aa25e3c0cd.png)
![screenshot - 24 09 2015 - 13 32 27](https://cloud.githubusercontent.com/assets/13997397/10072315/c3c49cda-62c0-11e5-9495-072b124ef0f6.png)

greetings :)

**Comment by rchatterjee** [comment]
Hey,

I cannot regenerate the error. Are you sure you have most updated master
[5719fe5c7655237bce  or 02292b7f16b9668e53]?

Here is my burteforce decryption effort results in,

(hvenv)[user@user] [master]$ bzcat ~/passwords/phpbb-withcount.txt.bz2 |
head -n20 | awk '{print $2}'| while read x; do echo $x '-->'
`./honey_client -getpass $x google.com`; done
123456 --> { "google.com": "karis1" }
password --> { "google.com": "PRINCE" }
phpbb --> { "google.com": "teamo" }
qwerty --> { "google.com": "sunshine" }
12345 --> { "google.com": "purple13" }
12345678 --> { "google.com": "roberto" }
letmein --> { "google.com": "101793" }
111111 --> { "google.com": "daniel01" }
1234 --> { "google.com": "052585" }
123456789 --> { "google.com": "140685" }
abc123 --> { "google.com": "chris" }
test --> { "google.com": "123456" }
123123 --> { "google.com": "jackson" }
123 --> { "google.com": "miller" }
monkey --> { "google.com": "superman" }
dragon --> { "google.com": "asaness" }
trustno1 --> { "google.com": "chanice" }
master --> { "google.com": "maisie" }
hello --> { "google.com": "hollister" }
1234567 --> { "google.com": "monkey" }

Or,
Try deleting the static/vault.db and regenerating the vault.
(I mean you will loose the passwords, but I am assuming you are using it
for experiment purpose :)).

Thanks,
- Rahul

On Thu, Sep 24, 2015 at 7:33 AM, benedict-beuscher <notifications@github.com

**Comment by benedict-beuscher** [comment]
that solved the problem. thank you! (2 more questions via mail :) )
